# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from pydantic import ConfigDict


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from pydantic import Field
from ..models.documentation_property import DocumentationProperty


try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class LegacyDocumentation(BaseModel):
    """LegacyDocumentation."""

    supported_states: List[DocumentationProperty] = Field(alias="supportedStates")
    configuration: List[DocumentationProperty]
    raw_data: List[DocumentationProperty] = Field(alias="rawData")
    __properties: ClassVar[List[str]] = ["supportedStates", "configuration", "rawData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Get the string representation of the model using alias."""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Get the JSON representation of the model using alias."""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict(), default=str)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LegacyDocumentation from a JSON string."""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        # pylint: disable=not-an-iterable, no-member, unsupported-membership-test
        # pylint has some issues with `field` https://github.com/pylint-dev/pylint/issues/7437, so disable some checks
        """Get the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in supported_states (list)
        _items = []
        if self.supported_states:
            for _item in self.supported_states:  # type: ignore
                if _item:
                    _items.append(_item.to_dict())
            _dict['supportedStates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in configuration (list)
        _items = []
        if self.configuration:
            for _item in self.configuration:  # type: ignore
                if _item:
                    _items.append(_item.to_dict())
            _dict['configuration'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in raw_data (list)
        _items = []
        if self.raw_data:
            for _item in self.raw_data:  # type: ignore
                if _item:
                    _items.append(_item.to_dict())
            _dict['rawData'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LegacyDocumentation from a dict."""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "supportedStates": [DocumentationProperty.from_dict(_item) for _item in obj.get("supportedStates")] if obj.get("supportedStates") is not None else None,  # type: ignore
            "configuration": [DocumentationProperty.from_dict(_item) for _item in obj.get("configuration")] if obj.get("configuration") is not None else None,  # type: ignore
            "rawData": [DocumentationProperty.from_dict(_item) for _item in obj.get("rawData")] if obj.get("rawData") is not None else None  # type: ignore
        })
        return _obj
