# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations
import re  # noqa: F401

from ..models.documentation import Documentation
from ..models.legacy_plug_request_metadata_documentation_any_of import (
    LegacyPlugRequestMetadataDocumentationAnyOf,
)

from typing import (
    Union,  # >=3.8
)
from typing_extensions import (
    Annotated,  # >=3.9
)


LegacyPlugRequestMetadataDocumentation = Union[
    Annotated[LegacyPlugRequestMetadataDocumentationAnyOf, ""],
    Annotated[Documentation, ""],
]
"""LegacyPlugRequestMetadataDocumentation."""
