# coding: utf-8
"""Waylay Function Registry: Service.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

version: 2.14.2

V2 API to build and deploy Waylay functions (plugs, webscripts, BYOML models).

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "2.14.2.20240802"

from .service import RegistryService

PLUGINS = [RegistryService]

__all__ = [
    "__version__",
    "RegistryService",
]
