# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.kfserving_response_v2 import KfservingResponseV2


class AltEmbeddedVersionIKfservingResponseV2(WaylayBaseModel):
    """Embedded representations of the _latest_ draft/published versions.."""

    draft: KfservingResponseV2 | None = None
    published: KfservingResponseV2 | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
