# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.deprecate_previous_policy_any_of import DeprecatePreviousPolicyAnyOf
from ..models.deprecate_previous_policy_any_of1 import DeprecatePreviousPolicyAnyOf1
from ..models.deprecate_previous_policy_any_of2 import DeprecatePreviousPolicyAnyOf2
from ..models.deprecate_previous_policy_any_of3 import DeprecatePreviousPolicyAnyOf3

DeprecatePreviousPolicy = Union[
    Annotated[DeprecatePreviousPolicyAnyOf, ""],
    Annotated[DeprecatePreviousPolicyAnyOf1, ""],
    Annotated[DeprecatePreviousPolicyAnyOf2, ""],
    Annotated[DeprecatePreviousPolicyAnyOf3, ""],
]
"""DeprecatePreviousPolicy."""
