# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class InvocationAttributesAuth(str, Enum):
    """Indicates what credentials are passed to provide a Waylay authorization context.."""

    WAYLAY = "waylay"
    NONE = "none"

    def __str__(self) -> str:
        return str(self.value)
