# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.invocation_attributes_auth import InvocationAttributesAuth


class InvocationAttributes(WaylayBaseModel):
    """InvocationAttributes."""

    auth: InvocationAttributesAuth
    task_context: StrictBool = Field(
        description="Indicates whether the task context attributes should be provided in `options.task`.",
        alias="taskContext",
    )
    node_context: StrictBool = Field(
        description="Indicates whether the node context attributes should be provided in `options.node`.",
        alias="nodeContext",
    )
    raw_data_context: StrictBool = Field(
        description="Indicates that the rawdata context attributes should be provided in `options.rawData`.",
        alias="rawDataContext",
    )
    callback: StrictBool = Field(
        description="Indicates that the plug implementer intends to use the callback mechanism."
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
