# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class LegacyPlugCreateQuery(WaylayBaseModel):
    """LegacyPlugCreateQuery."""

    var_async: StrictBool | None = Field(
        default=False,
        description="If this is set to <code>true</code>, the server will start the required job actions asynchronously and return a <code>202</code> <em>Accepted</em> response. Otherwise, the request will block until the job actions are completed, or a timeout occurs.",
        alias="async",
    )
    dry_run: StrictBool | None = Field(
        default=None,
        description="If set to <code>true</true>, only validates the incoming request.",
        alias="dryRun",
    )
    scale_to_zero: StrictBool | None = Field(
        default=None,
        description="If set to <code>true</true>, scales the function to zero after successful deployment.",
        alias="scaleToZero",
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
