# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Any

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.plug_property_data_type import PlugPropertyDataType
from ..models.plug_property_format import PlugPropertyFormat


class PlugProperty(WaylayBaseModel):
    """Interface specification of a plug property.."""

    name: StrictStr = Field(description="The name of a plug input or output property.")
    data_type: PlugPropertyDataType | None = Field(default=None, alias="dataType")
    mandatory: StrictBool | None = Field(
        default=None, description="If <code>true</code> this property is required."
    )
    format: PlugPropertyFormat | None = None
    default_value: Any | None = Field(default=None, alias="defaultValue")

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
