# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

TimestampAge = Union[
    Annotated[str, "An ISO8601 period expression"],
    Annotated[
        str,
        "An duration expression. A numeric value without unit is interpreted as milliseconds.",
    ],
]
"""A timestamp expressed as a age relative to now."""
