# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.function_deploy_overrides_type import FunctionDeployOverridesType
from ..models.function_meta import FunctionMeta
from ..models.semantic_version_range import SemanticVersionRange


class WebscriptManifestPatch(WaylayBaseModel):
    """Patch attributes to merge into an existing webscript manifest.."""

    private: StrictBool | None = Field(
        default=None,
        description="If <code>true</code> this webscript will require authentication.",
    )
    allow_hmac: StrictBool | None = Field(
        default=None,
        description="If <code>true</code> this webscript will support authentication with a <em>HMAC</em> key, available as the <code>secret</code> attribute of the deployed webscript entity.",
        alias="allowHmac",
    )
    runtime_version: SemanticVersionRange | None = Field(
        default=None, alias="runtimeVersion"
    )
    metadata: FunctionMeta | None = None
    runtime: StrictStr | None = None
    deploy: FunctionDeployOverridesType | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
