# coding: utf-8
"""Waylay Function Registry models.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.alt_embedded_version_i_webscript_response_with_invoke_link_v2 import (
    AltEmbeddedVersionIWebscriptResponseWithInvokeLinkV2,
)


class WithEmbeddedAltVersionsIWebscriptResponseWithInvokeLinkV2(WaylayBaseModel):
    """WithEmbeddedAltVersionsIWebscriptResponseWithInvokeLinkV2."""

    embedded: AltEmbeddedVersionIWebscriptResponseWithInvokeLinkV2 | None = Field(
        default=None, alias="_embedded"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
