# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.any_function_response import (
        AnyFunctionResponse,
    )

    AnyFunctionResponseAdapter = TypeAdapter(AnyFunctionResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

any_function_response_model_schema = json.loads(
    r"""{
  "anyOf" : [ {
    "$ref" : "#/components/schemas/PlugResponseV2"
  }, {
    "$ref" : "#/components/schemas/KfservingResponseV2"
  }, {
    "$ref" : "#/components/schemas/WebscriptResponseV2"
  } ]
}
""",
    object_hook=with_example_provider,
)
any_function_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

any_function_response_faker = JSF(
    any_function_response_model_schema, allow_none_optionals=1
)


class AnyFunctionResponseStub:
    """AnyFunctionResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return any_function_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "AnyFunctionResponse":
        """Create AnyFunctionResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AnyFunctionResponseAdapter.validate_python(cls.create_json())
