# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.any_job_status import AnyJobStatus

    AnyJobStatusAdapter = TypeAdapter(AnyJobStatus)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for AnyJobStatus not available: {exc}")
    MODELS_AVAILABLE = False

any_job_status_model_schema = json.loads(r"""{
  "anyOf" : [ {
    "$ref" : "#/components/schemas/BuildJobStatus"
  }, {
    "$ref" : "#/components/schemas/DeployJobStatus"
  }, {
    "$ref" : "#/components/schemas/VerifyJobStatus"
  }, {
    "$ref" : "#/components/schemas/UndeployJobStatus"
  }, {
    "$ref" : "#/components/schemas/ScaleJobStatus"
  }, {
    "$ref" : "#/components/schemas/BatchJobStatus"
  } ]
}
""")
any_job_status_model_schema.update({"definitions": MODEL_DEFINITIONS})

any_job_status_faker = JSF(any_job_status_model_schema, allow_none_optionals=1)


class AnyJobStatusStub:
    """AnyJobStatus unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return any_job_status_faker.generate()

    @classmethod
    def create_instance(cls) -> "AnyJobStatus":
        """Create AnyJobStatus stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AnyJobStatusAdapter.validate_python(cls.create_json())
