# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.archive_format import ArchiveFormat

    ArchiveFormatAdapter = TypeAdapter(ArchiveFormat)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

archive_format_model_schema = json.loads(
    r"""{
  "type" : "string",
  "enum" : [ "node", "python", "golang", "byoml", "native" ]
}
""",
    object_hook=with_example_provider,
)
archive_format_model_schema.update({"definitions": MODEL_DEFINITIONS})

archive_format_faker = JSF(archive_format_model_schema, allow_none_optionals=1)


class ArchiveFormatStub:
    """ArchiveFormat unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return archive_format_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "ArchiveFormat":
        """Create ArchiveFormat stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ArchiveFormatAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ArchiveFormatAdapter.validate_python(
            json, context={"skip_validation": True}
        )
