# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.completed_event_data import CompletedEventData


from .any_job_result_stub import AnyJobResultStub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class CompletedEventDataStub:
    """CompletedEventData unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> CompletedEventData:
        """Create CompletedEventData stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return CompletedEventData(
                prev="completed", return_value=AnyJobResultStub.create_instance()
            )
        else:
            return CompletedEventData(return_value=AnyJobResultStub.create_instance())
