# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.content_validation_listing import ContentValidationListing

from .asset_summary_with_hal_link_stub import AssetSummaryWithHALLinkStub
from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from waylay.services.registry.models.asset_summary_with_hal_link import AssetSummaryWithHALLink


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class ContentValidationListingStub:
    """ContentValidationListing unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> ContentValidationListing:
        """Create ContentValidationListing stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return ContentValidationListing(
                assets=[AssetSummaryWithHALLinkStub.create_instance()]
            )
        else:
            return ContentValidationListing(
                assets=[AssetSummaryWithHALLinkStub.create_instance()]
            )
