# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.create_plug_async_response import (
        CreatePlugAsyncResponse,
    )

    CreatePlugAsyncResponseAdapter = TypeAdapter(CreatePlugAsyncResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

create_plug_async_response_model_schema = json.loads(
    r"""{
  "required" : [ "_links", "entity", "message" ],
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string"
    },
    "_links" : {
      "$ref" : "#/components/schemas/JobHALLinks"
    },
    "entity" : {
      "$ref" : "#/components/schemas/PlugManifest"
    }
  },
  "description" : "Successful Response"
}
""",
    object_hook=with_example_provider,
)
create_plug_async_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

create_plug_async_response_faker = JSF(
    create_plug_async_response_model_schema, allow_none_optionals=1
)


class CreatePlugAsyncResponseStub:
    """CreatePlugAsyncResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return create_plug_async_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "CreatePlugAsyncResponse":
        """Create CreatePlugAsyncResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return CreatePlugAsyncResponseAdapter.validate_python(cls.create_json())
