# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.create_kf_serving_async_response import (
        CreateKFServingAsyncResponse,
    )

    CreateKFServingAsyncResponseAdapter = TypeAdapter(CreateKFServingAsyncResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for CreateKFServingAsyncResponse not available: {exc}")
    MODELS_AVAILABLE = False

create_kf_serving_async_response_model_schema = json.loads(r"""{
  "required" : [ "_links", "entity", "message" ],
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string"
    },
    "_links" : {
      "$ref" : "#/components/schemas/JobHALLinks"
    },
    "entity" : {
      "$ref" : "#/components/schemas/KFServingManifest"
    }
  },
  "description" : "Model Deployment Initiated"
}
""")
create_kf_serving_async_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

create_kf_serving_async_response_faker = JSF(
    create_kf_serving_async_response_model_schema, allow_none_optionals=1
)


class CreateKFServingAsyncResponseStub:
    """CreateKFServingAsyncResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return create_kf_serving_async_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "CreateKFServingAsyncResponse":
        """Create CreateKFServingAsyncResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return CreateKFServingAsyncResponseAdapter.validate_python(cls.create_json())
