# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.deprecate_previous_query import DeprecatePreviousQuery


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from waylay.services.registry.models.deprecate_previous_policy import DeprecatePreviousPolicy


class DeprecatePreviousQueryStub:
    """DeprecatePreviousQuery unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> DeprecatePreviousQuery:
        """Create DeprecatePreviousQuery stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return DeprecatePreviousQuery(
                deprecate_previous='none'
            )
        else:
            return DeprecatePreviousQuery(
            )
