# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.dry_run_query import DryRunQuery

    DryRunQueryAdapter = TypeAdapter(DryRunQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

dry_run_query_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "dryRun" : {
      "type" : "boolean",
      "description" : "If set to <code>true</code>, validates the deployment conditions, but does not change anything."
    }
  },
  "additionalProperties" : false
}
""",
    object_hook=with_example_provider,
)
dry_run_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

dry_run_query_faker = JSF(dry_run_query_model_schema, allow_none_optionals=1)


class DryRunQueryStub:
    """DryRunQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return dry_run_query_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "DryRunQuery":
        """Create DryRunQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(DryRunQueryAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DryRunQueryAdapter.validate_python(
            json, context={"skip_validation": True}
        )
