# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.event_with_close_sse import EventWithCloseSSE


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from waylay.services.registry.models.job_event_sse import JobEventSSE
from waylay.services.registry.models.keep_alive_event_sse import KeepAliveEventSSE
from waylay.services.registry.models.stream_closing import StreamClosing
from waylay.services.registry.models.stream_ready import StreamReady


from .stream_ready_stub import StreamReadyStub

from .job_event_sse_stub import JobEventSSEStub

from .keep_alive_event_sse_stub import KeepAliveEventSSEStub

from .stream_closing_stub import StreamClosingStub


class EventWithCloseSSEStub:
    """EventWithCloseSSE unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> EventWithCloseSSE:
        """Create EventWithCloseSSE stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        # return instance of first type from `anyOf`
        return EventWithCloseSSE(StreamReadyStub.create_instance(include_optional=include_optional))
