# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.event_keep_alive import EventKeepAlive

    EventKeepAliveAdapter = TypeAdapter(EventKeepAlive)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for EventKeepAlive not available: {exc}")
    MODELS_AVAILABLE = False

event_keep_alive_model_schema = json.loads(r"""{
  "type" : "string",
  "enum" : [ "keep-alive" ]
}
""")
event_keep_alive_model_schema.update({"definitions": MODEL_DEFINITIONS})

event_keep_alive_faker = JSF(event_keep_alive_model_schema, allow_none_optionals=1)


class EventKeepAliveStub:
    """EventKeepAlive unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return event_keep_alive_faker.generate()

    @classmethod
    def create_instance(cls) -> "EventKeepAlive":
        """Create EventKeepAlive stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return EventKeepAliveAdapter.validate_python(cls.create_json())
