# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.function_entity_query import FunctionEntityQuery


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class FunctionEntityQueryStub:
    """FunctionEntityQuery unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> FunctionEntityQuery:
        """Create FunctionEntityQuery stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return FunctionEntityQuery(name="", archive_format=["node"], runtime=[""])
        else:
            return FunctionEntityQuery()
