# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from waylay.services.registry.models.get_model_response_v2 import GetModelResponseV2
from .kfserving_response_v2_stub import KfservingResponseV2Stub

from .get_plug_response_v2_links_stub import GetPlugResponseV2LinksStub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class GetModelResponseV2Stub:
    """GetModelResponseV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> GetModelResponseV2:
        """Create GetModelResponseV2 stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return GetModelResponseV2(
                entity=KfservingResponseV2Stub.create_instance(),
                links=GetPlugResponseV2LinksStub.create_instance(),
            )
        else:
            return GetModelResponseV2(
                entity=KfservingResponseV2Stub.create_instance(),
                links=GetPlugResponseV2LinksStub.create_instance(),
            )
