# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.get_runtime_by_name_query import (
    GetRuntimeByNameQuery,
)
from .semantic_version_range_stub import SemanticVersionRangeStub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class GetRuntimeByNameQueryStub:
    """GetRuntimeByNameQuery unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> GetRuntimeByNameQuery:
        """Create GetRuntimeByNameQuery stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return GetRuntimeByNameQuery(
                version=SemanticVersionRangeStub.create_instance(),
                include_deprecated=True,
                function_type=["plugs"],
                archive_format=["node"],
            )
        else:
            return GetRuntimeByNameQuery()
