# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.get_plug_response_v2 import GetPlugResponseV2
from .plug_response_v2_stub import PlugResponseV2Stub

from .get_plug_response_v2_links_stub import GetPlugResponseV2LinksStub

from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from pydantic import Field
from waylay.services.registry.models.get_plug_response_v2_links import GetPlugResponseV2Links
from waylay.services.registry.models.plug_response_v2 import PlugResponseV2


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class GetPlugResponseV2Stub:
    """GetPlugResponseV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> GetPlugResponseV2:
        """Create GetPlugResponseV2 stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return GetPlugResponseV2(
                entity=PlugResponseV2Stub.create_instance(),
                links=GetPlugResponseV2LinksStub.create_instance()
            )
        else:
            return GetPlugResponseV2(
                entity=PlugResponseV2Stub.create_instance(),
                links=GetPlugResponseV2LinksStub.create_instance()
            )
