# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.job_state_waiting import JobStateWaiting

    JobStateWaitingAdapter = TypeAdapter(JobStateWaiting)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for JobStateWaiting not available: {exc}")
    MODELS_AVAILABLE = False

job_state_waiting_model_schema = json.loads(r"""{
  "title" : "JobStateWaiting",
  "type" : "string",
  "description" : "The job has been queued for execution, but might be waiting because of rate limiting.",
  "enum" : [ "waiting" ]
}
""")
job_state_waiting_model_schema.update({"definitions": MODEL_DEFINITIONS})

job_state_waiting_faker = JSF(job_state_waiting_model_schema, allow_none_optionals=1)


class JobStateWaitingStub:
    """JobStateWaiting unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return job_state_waiting_faker.generate()

    @classmethod
    def create_instance(cls) -> "JobStateWaiting":
        """Create JobStateWaiting stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return JobStateWaitingAdapter.validate_python(cls.create_json())
