# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.job_events_and_function_hal_link import (
        JobEventsAndFunctionHALLink,
    )

    JobEventsAndFunctionHALLinkAdapter = TypeAdapter(JobEventsAndFunctionHALLink)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

job_events_and_function_hal_link_model_schema = json.loads(
    r"""{
  "title" : "JobEventsAndFunctionHALLink",
  "description" : "HAL links to related actions.",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/Plug"
  }, {
    "$ref" : "#/components/schemas/Webscript"
  }, {
    "$ref" : "#/components/schemas/Model"
  }, {
    "$ref" : "#/components/schemas/JobEventsHALLink"
  } ]
}
""",
    object_hook=with_example_provider,
)
job_events_and_function_hal_link_model_schema.update({"definitions": MODEL_DEFINITIONS})

job_events_and_function_hal_link_faker = JSF(
    job_events_and_function_hal_link_model_schema, allow_none_optionals=1
)


class JobEventsAndFunctionHALLinkStub:
    """JobEventsAndFunctionHALLink unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return job_events_and_function_hal_link_faker.generate()

    @classmethod
    def create_instance(cls) -> "JobEventsAndFunctionHALLink":
        """Create JobEventsAndFunctionHALLink stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return JobEventsAndFunctionHALLinkAdapter.validate_python(cls.create_json())
