# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.job_type_build import JobTypeBuild

    JobTypeBuildAdapter = TypeAdapter(JobTypeBuild)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

job_type_build_model_schema = json.loads(
    r"""{
  "title" : "JobTypeBuild",
  "type" : "string",
  "description" : "Build",
  "enum" : [ "build" ]
}
""",
    object_hook=with_example_provider,
)
job_type_build_model_schema.update({"definitions": MODEL_DEFINITIONS})

job_type_build_faker = JSF(job_type_build_model_schema, allow_none_optionals=1)


class JobTypeBuildStub:
    """JobTypeBuild unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return job_type_build_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "JobTypeBuild":
        """Create JobTypeBuild stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                JobTypeBuildAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return JobTypeBuildAdapter.validate_python(
            json, context={"skip_validation": True}
        )
