# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.job_type_schema import JobTypeSchema


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from waylay.services.registry.models.job_type_batch import JobTypeBatch
from waylay.services.registry.models.job_type_build import JobTypeBuild
from waylay.services.registry.models.job_type_deploy import JobTypeDeploy
from waylay.services.registry.models.job_type_scale import JobTypeScale
from waylay.services.registry.models.job_type_undeploy import JobTypeUndeploy
from waylay.services.registry.models.job_type_verify import JobTypeVerify


from .job_type_build_stub import JobTypeBuildStub

from .job_type_deploy_stub import JobTypeDeployStub

from .job_type_verify_stub import JobTypeVerifyStub

from .job_type_undeploy_stub import JobTypeUndeployStub

from .job_type_scale_stub import JobTypeScaleStub

from .job_type_batch_stub import JobTypeBatchStub


class JobTypeSchemaStub:
    """JobTypeSchema unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> JobTypeSchema:
        """Create JobTypeSchema stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        # return instance of first type from `anyOf`
        return JobTypeSchema(JobTypeBuildStub.create_instance(include_optional=include_optional))
