# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.job_status import JobStatus


from .job_status_progress_stub import JobStatusProgressStub


from .parent_keys_stub import ParentKeysStub


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from waylay.services.registry.models.job_status_progress import JobStatusProgress
from waylay.services.registry.models.parent_keys import ParentKeys


class JobStatusStub:
    """JobStatus unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> JobStatus:
        """Create JobStatus stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return JobStatus(
                id='',
                name='',
                progress=JobStatusProgressStub.create_instance(),
                attempts_made=1.337,
                finished_on=datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                processed_on=datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                failed_reason='',
                parent=ParentKeysStub.create_instance(),
                delay=1.337
            )
        else:
            return JobStatus(
                id='',
                name='',
                progress=JobStatusProgressStub.create_instance(),
                attempts_made=1.337,
            )
