# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.job_query import JobQuery


from .job_type_schema_stub import JobTypeSchemaStub

from .job_state_result_stub import JobStateResultStub

from .function_type_stub import FunctionTypeStub
from .timestamp_spec_stub import TimestampSpecStub

from .timestamp_spec_stub import TimestampSpecStub


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel
from pydantic import Field
from typing_extensions import Annotated
from waylay.services.registry.models.function_type import FunctionType
from waylay.services.registry.models.job_state_result import JobStateResult
from waylay.services.registry.models.job_type_schema import JobTypeSchema
from waylay.services.registry.models.timestamp_spec import TimestampSpec


class JobQueryStub:
    """JobQuery unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> JobQuery:
        """Create JobQuery stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return JobQuery(
                limit=0,
                type=[JobTypeSchemaStub.create_instance()],
                state=[JobStateResultStub.create_instance()],
                function_type=['plugs'],
                created_before=TimestampSpecStub.create_instance(),
                created_after=TimestampSpecStub.create_instance()
            )
        else:
            return JobQuery(
            )
