# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.jobs_hal_link import JobsHALLink

    JobsHALLinkAdapter = TypeAdapter(JobsHALLink)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

jobs_hal_link_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "jobs" : {
      "$ref" : "#/components/schemas/HALLink"
    }
  }
}
""",
    object_hook=with_example_provider,
)
jobs_hal_link_model_schema.update({"definitions": MODEL_DEFINITIONS})

jobs_hal_link_faker = JSF(jobs_hal_link_model_schema, allow_none_optionals=1)


class JobsHALLinkStub:
    """JobsHALLink unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return jobs_hal_link_faker.generate()

    @classmethod
    def create_instance(cls) -> "JobsHALLink":
        """Create JobsHALLink stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return JobsHALLinkAdapter.validate_python(cls.create_json())
