# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.keep_alive_event_sse import KeepAliveEventSSE


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from waylay.services.registry.models.event_keep_alive import EventKeepAlive


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class KeepAliveEventSSEStub:
    """KeepAliveEventSSE unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> KeepAliveEventSSE:
        """Create KeepAliveEventSSE stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return KeepAliveEventSSE(
                event='keep-alive',
                data=''
            )
        else:
            return KeepAliveEventSSE(
                event='keep-alive',
            )
