# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.latest_plug_versions_query_v2 import LatestPlugVersionsQueryV2

from .tags_filter_stub import TagsFilterStub


from .status_filter_stub import StatusFilterStub
from .semantic_version_range_stub import SemanticVersionRangeStub


from .timestamp_spec_stub import TimestampSpecStub

from .timestamp_spec_stub import TimestampSpecStub

from .timestamp_spec_stub import TimestampSpecStub

from .timestamp_spec_stub import TimestampSpecStub


from .archive_format_stub import ArchiveFormatStub


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from waylay.services.registry.models.latest_plug_versions_query import LatestPlugVersionsQuery
from waylay.services.registry.models.latest_plugs_query import LatestPlugsQuery


from .latest_plug_versions_query_stub import LatestPlugVersionsQueryStub

from .latest_plugs_query_stub import LatestPlugsQueryStub


class LatestPlugVersionsQueryV2Stub:
    """LatestPlugVersionsQueryV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> LatestPlugVersionsQueryV2:
        """Create LatestPlugVersionsQueryV2 stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        # return instance of first type from `anyOf`
        return LatestPlugVersionsQueryV2(LatestPlugVersionsQueryStub.create_instance(include_optional=include_optional))
