# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.legacy_documentation_request import (
        LegacyDocumentationRequest,
    )

    LegacyDocumentationRequestAdapter = TypeAdapter(LegacyDocumentationRequest)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

legacy_documentation_request_model_schema = json.loads(
    r"""{
  "required" : [ "configuration", "rawData", "supportedStates" ],
  "type" : "object",
  "properties" : {
    "description" : {
      "type" : "string"
    },
    "supportedStates" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/DocumentationProperty"
      }
    },
    "configuration" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/DocumentationProperty"
      }
    },
    "rawData" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/DocumentationProperty"
      }
    }
  },
  "additionalProperties" : false
}
""",
    object_hook=with_example_provider,
)
legacy_documentation_request_model_schema.update({"definitions": MODEL_DEFINITIONS})

legacy_documentation_request_faker = JSF(
    legacy_documentation_request_model_schema, allow_none_optionals=1
)


class LegacyDocumentationRequestStub:
    """LegacyDocumentationRequest unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return legacy_documentation_request_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "LegacyDocumentationRequest":
        """Create LegacyDocumentationRequest stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                LegacyDocumentationRequestAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return LegacyDocumentationRequestAdapter.validate_python(
            json, context={"skip_validation": True}
        )
