# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.legacy_function_meta import LegacyFunctionMeta


from .tag_stub import TagStub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class LegacyFunctionMetaStub:
    """LegacyFunctionMeta unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> LegacyFunctionMeta:
        """Create LegacyFunctionMeta stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return LegacyFunctionMeta(
                author="",
                description="",
                category="",
                tags=[TagStub.create_instance()],
                icon_url="",
                friendly_name="",
            )
        else:
            return LegacyFunctionMeta()
