# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.legacy_configuration_response_object import (
        LegacyConfigurationResponseObject,
    )

    LegacyConfigurationResponseObjectAdapter = TypeAdapter(
        LegacyConfigurationResponseObject
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

legacy_configuration_response_object_model_schema = json.loads(
    r"""{
  "title" : "LegacyConfigurationResponseObject",
  "required" : [ "name", "type" ],
  "type" : "object",
  "properties" : {
    "name" : {
      "title" : "name",
      "type" : "string"
    },
    "type" : {
      "$ref" : "#/components/schemas/PlugPropertyDataType"
    },
    "mandatory" : {
      "title" : "mandatory",
      "type" : "boolean"
    },
    "format" : {
      "$ref" : "#/components/schemas/LegacyConfigurationObject_format"
    },
    "defaultValue" : {
      "$ref" : "#/components/schemas/DefaultValue"
    },
    "sensitive" : {
      "title" : "sensitive",
      "type" : "boolean"
    }
  }
}
""",
    object_hook=with_example_provider,
)
legacy_configuration_response_object_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

legacy_configuration_response_object_faker = JSF(
    legacy_configuration_response_object_model_schema, allow_none_optionals=1
)


class LegacyConfigurationResponseObjectStub:
    """LegacyConfigurationResponseObject unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return legacy_configuration_response_object_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "LegacyConfigurationResponseObject":
        """Create LegacyConfigurationResponseObject stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                LegacyConfigurationResponseObjectAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return LegacyConfigurationResponseObjectAdapter.validate_python(
            json, context={"skip_validation": True}
        )
