# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.named_parameters_typeof_from_legacy_documentation import NamedParametersTypeofFromLegacyDocumentation

from .legacy_plug_request_metadata_documentation_stub import LegacyPlugRequestMetadataDocumentationStub

from .plug_interface_stub import PlugInterfaceStub


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from waylay.services.registry.models.legacy_plug_request_metadata_documentation import LegacyPlugRequestMetadataDocumentation
from waylay.services.registry.models.plug_interface import PlugInterface


class NamedParametersTypeofFromLegacyDocumentationStub:
    """NamedParametersTypeofFromLegacyDocumentation unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> NamedParametersTypeofFromLegacyDocumentation:
        """Create NamedParametersTypeofFromLegacyDocumentation stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return NamedParametersTypeofFromLegacyDocumentation(
                legacy_documentation=LegacyPlugRequestMetadataDocumentationStub.create_instance(),
                current_interface=PlugInterfaceStub.create_instance()
            )
        else:
            return NamedParametersTypeofFromLegacyDocumentation(
            )
