# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.patch_interface_query import (
        PatchInterfaceQuery,
    )

    PatchInterfaceQueryAdapter = TypeAdapter(PatchInterfaceQuery)
    MODELS_AVAILABLE = True
except ImportError:
    MODELS_AVAILABLE = False

patch_interface_query_model_schema = json.loads(r"""{
  "type" : "object",
  "properties" : {
    "comment" : {
      "type" : "string",
      "description" : "An optional user-specified comment corresponding to the operation."
    }
  },
  "additionalProperties" : false
}
""")
patch_interface_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

patch_interface_query_faker = JSF(
    patch_interface_query_model_schema, allow_none_optionals=1
)


class PatchInterfaceQueryStub:
    """PatchInterfaceQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return patch_interface_query_faker.generate()

    @classmethod
    def create_instance(cls) -> "PatchInterfaceQuery":
        """Create PatchInterfaceQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PatchInterfaceQueryAdapter.validate_python(cls.create_json())
