# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.plug_delete_force_query import (
        PlugDeleteForceQuery,
    )

    PlugDeleteForceQueryAdapter = TypeAdapter(PlugDeleteForceQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for PlugDeleteForceQuery not available: {exc}")
    MODELS_AVAILABLE = False

plug_delete_force_query_model_schema = json.loads(r"""{
  "type" : "object",
  "properties" : {
    "force" : {
      "type" : "boolean",
      "description" : "If <code>true</code>, the plug version(s) will be undeployed and removed. Otherwise, the plug version(s) will only be <code>deprecated</code>, i.e removed from regular listings."
    }
  },
  "additionalProperties" : false
}
""")
plug_delete_force_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

plug_delete_force_query_faker = JSF(
    plug_delete_force_query_model_schema, allow_none_optionals=1
)


class PlugDeleteForceQueryStub:
    """PlugDeleteForceQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return plug_delete_force_query_faker.generate()

    @classmethod
    def create_instance(cls) -> "PlugDeleteForceQuery":
        """Create PlugDeleteForceQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PlugDeleteForceQueryAdapter.validate_python(cls.create_json())
