# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.plug_type import PlugType

    PlugTypeAdapter = TypeAdapter(PlugType)
    MODELS_AVAILABLE = True
except ImportError:
    MODELS_AVAILABLE = False

plug_type_model_schema = json.loads(r"""{
  "title" : "PlugType",
  "type" : "string",
  "enum" : [ "sensor", "actuator", "transformer" ]
}
""")
plug_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

plug_type_faker = JSF(plug_type_model_schema, allow_none_optionals=1)


class PlugTypeStub:
    """PlugType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return plug_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "PlugType":
        """Create PlugType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PlugTypeAdapter.validate_python(cls.create_json())
