# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.plug_type_query import PlugTypeQuery

    PlugTypeQueryAdapter = TypeAdapter(PlugTypeQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

plug_type_query_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "type" : {
      "$ref" : "#/components/schemas/PlugType"
    }
  },
  "additionalProperties" : false
}
""",
    object_hook=with_example_provider,
)
plug_type_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

plug_type_query_faker = JSF(plug_type_query_model_schema, allow_none_optionals=1)


class PlugTypeQueryStub:
    """PlugTypeQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return plug_type_query_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "PlugTypeQuery":
        """Create PlugTypeQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                PlugTypeQueryAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return PlugTypeQueryAdapter.validate_python(
            json, context={"skip_validation": True}
        )
