# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.post_model_job_async_response_v2 import (
        PostModelJobAsyncResponseV2,
    )

    PostModelJobAsyncResponseV2Adapter = TypeAdapter(PostModelJobAsyncResponseV2)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for PostModelJobAsyncResponseV2 not available: {exc}")
    MODELS_AVAILABLE = False

post_model_job_async_response_v2_model_schema = json.loads(r"""{
  "required" : [ "_links", "entity", "message" ],
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string"
    },
    "_links" : {
      "$ref" : "#/components/schemas/JobHALLinks"
    },
    "entity" : {
      "$ref" : "#/components/schemas/KfservingResponseV2"
    }
  },
  "description" : "Model Deployment Initiated"
}
""")
post_model_job_async_response_v2_model_schema.update({"definitions": MODEL_DEFINITIONS})

post_model_job_async_response_v2_faker = JSF(
    post_model_job_async_response_v2_model_schema, allow_none_optionals=1
)


class PostModelJobAsyncResponseV2Stub:
    """PostModelJobAsyncResponseV2 unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return post_model_job_async_response_v2_faker.generate()

    @classmethod
    def create_instance(cls) -> "PostModelJobAsyncResponseV2":
        """Create PostModelJobAsyncResponseV2 stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PostModelJobAsyncResponseV2Adapter.validate_python(cls.create_json())
