# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.post_model_job_sync_response_v2 import (
    PostModelJobSyncResponseV2,
)


from .kfserving_response_v2_stub import KfservingResponseV2Stub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class PostModelJobSyncResponseV2Stub:
    """PostModelJobSyncResponseV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> PostModelJobSyncResponseV2:
        """Create PostModelJobSyncResponseV2 stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return PostModelJobSyncResponseV2(
                message="", entity=KfservingResponseV2Stub.create_instance()
            )
        else:
            return PostModelJobSyncResponseV2(
                message="", entity=KfservingResponseV2Stub.create_instance()
            )
