# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from waylay.services.registry.models.rebuild_model_sync_response_v2 import (
    RebuildModelSyncResponseV2,
)


from .job_causes_stub import JobCausesStub

from .kfserving_response_v2_stub import KfservingResponseV2Stub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class RebuildModelSyncResponseV2Stub:
    """RebuildModelSyncResponseV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> RebuildModelSyncResponseV2:
        """Create RebuildModelSyncResponseV2 stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return RebuildModelSyncResponseV2(
                message="",
                causes=JobCausesStub.create_instance(),
                entity=KfservingResponseV2Stub.create_instance(),
            )
        else:
            return RebuildModelSyncResponseV2(
                message="",
                causes=JobCausesStub.create_instance(),
                entity=KfservingResponseV2Stub.create_instance(),
            )
