# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from waylay.services.registry.models.rebuild_model_async_response_v2 import (
    RebuildModelAsyncResponseV2,
)


from .job_hal_links_stub import JobHALLinksStub

from .job_causes_stub import JobCausesStub

from .kfserving_response_v2_stub import KfservingResponseV2Stub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class RebuildModelAsyncResponseV2Stub:
    """RebuildModelAsyncResponseV2 unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> RebuildModelAsyncResponseV2:
        """Create RebuildModelAsyncResponseV2 stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return RebuildModelAsyncResponseV2(
                message="",
                links=JobHALLinksStub.create_instance(),
                causes=JobCausesStub.create_instance(),
                entity=KfservingResponseV2Stub.create_instance(),
            )
        else:
            return RebuildModelAsyncResponseV2(
                message="",
                links=JobHALLinksStub.create_instance(),
                causes=JobCausesStub.create_instance(),
                entity=KfservingResponseV2Stub.create_instance(),
            )
