# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.runtime_version_response import RuntimeVersionResponse

from .compiled_runtime_version_stub import CompiledRuntimeVersionStub


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from waylay.services.registry.models.compiled_runtime_version import CompiledRuntimeVersion


class RuntimeVersionResponseStub:
    """RuntimeVersionResponse unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> RuntimeVersionResponse:
        """Create RuntimeVersionResponse stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return RuntimeVersionResponse(
                runtime=CompiledRuntimeVersionStub.create_instance()
            )
        else:
            return RuntimeVersionResponse(
                runtime=CompiledRuntimeVersionStub.create_instance()
            )
