# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.runtime_version_status import RuntimeVersionStatus


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictBool
from pydantic import Field


class RuntimeVersionStatusStub:
    """RuntimeVersionStatus unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> RuntimeVersionStatus:
        """Create RuntimeVersionStatus stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return RuntimeVersionStatus(
                deprecated=True,
                upgradable=True
            )
        else:
            return RuntimeVersionStatus(
                deprecated=True,
                upgradable=True
            )
