# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from waylay.services.registry.models.runtime_name_query import RuntimeNameQuery


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class RuntimeNameQueryStub:
    """RuntimeNameQuery unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> RuntimeNameQuery:
        """Create RuntimeNameQuery stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return RuntimeNameQuery(
                name="node*", function_type=["plugs"], archive_format=["node"]
            )
        else:
            return RuntimeNameQuery()
