# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.runtime_name_query import RuntimeNameQuery

    RuntimeNameQueryAdapter = TypeAdapter(RuntimeNameQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

runtime_name_query_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string",
      "description" : "If set, filters on the <code>name</code> of a runtime. Supports <code>*</code> and <code>?</code> wildcards and is case-insensitive.",
      "example" : "node*"
    },
    "functionType" : {
      "type" : "array",
      "description" : "If set, filters on the <code>functionType</code> of a runtime. Uses an exact match.",
      "example" : "plugs",
      "items" : {
        "$ref" : "#/components/schemas/FunctionType"
      }
    },
    "archiveFormat" : {
      "type" : "array",
      "description" : "If set, filters on the <code>archiveFormat</code> of a runtime. Uses an exact match.",
      "example" : "node",
      "items" : {
        "$ref" : "#/components/schemas/ArchiveFormat"
      }
    }
  },
  "additionalProperties" : false
}
""",
    object_hook=with_example_provider,
)
runtime_name_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

runtime_name_query_faker = JSF(runtime_name_query_model_schema, allow_none_optionals=1)


class RuntimeNameQueryStub:
    """RuntimeNameQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return runtime_name_query_faker.generate()

    @classmethod
    def create_instance(cls) -> "RuntimeNameQuery":
        """Create RuntimeNameQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return RuntimeNameQueryAdapter.validate_python(cls.create_json())
