# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.scale_args import ScaleArgs

    ScaleArgsAdapter = TypeAdapter(ScaleArgs)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

scale_args_model_schema = json.loads(
    r"""{
  "title" : "ScaleArgs",
  "required" : [ "endpoint", "namespace", "replicas", "runtimeName", "runtimeVersion" ],
  "type" : "object",
  "properties" : {
    "namespace" : {
      "title" : "namespace",
      "type" : "string",
      "description" : "The (openfaas) namespace for the target function."
    },
    "endpoint" : {
      "title" : "endpoint",
      "type" : "string",
      "description" : "The (openfaas) endpoint service name"
    },
    "runtimeName" : {
      "$ref" : "#/components/schemas/Runtime"
    },
    "runtimeVersion" : {
      "$ref" : "#/components/schemas/SemanticVersion"
    },
    "revision" : {
      "title" : "revision",
      "type" : "string",
      "description" : "The revision hash of the current (draft) function revision"
    },
    "replicas" : {
      "title" : "replicas",
      "type" : "number",
      "description" : "Number of target replicas"
    }
  },
  "description" : "Input argument to an (openfaas) scale job for a function."
}
""",
    object_hook=with_example_provider,
)
scale_args_model_schema.update({"definitions": MODEL_DEFINITIONS})

scale_args_faker = JSF(scale_args_model_schema, allow_none_optionals=1)


class ScaleArgsStub:
    """ScaleArgs unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return scale_args_faker.generate()

    @classmethod
    def create_instance(cls) -> "ScaleArgs":
        """Create ScaleArgs stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ScaleArgsAdapter.validate_python(cls.create_json())
