# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.status_any import StatusAny

    StatusAnyAdapter = TypeAdapter(StatusAny)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for StatusAny not available: {exc}")
    MODELS_AVAILABLE = False

status_any_model_schema = json.loads(r"""{
  "type" : "string",
  "description" : "Includes *all* statuses (including `undeployed`) as a filter",
  "enum" : [ "any" ]
}
""")
status_any_model_schema.update({"definitions": MODEL_DEFINITIONS})

status_any_faker = JSF(status_any_model_schema, allow_none_optionals=1)


class StatusAnyStub:
    """StatusAny unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return status_any_faker.generate()

    @classmethod
    def create_instance(cls) -> "StatusAny":
        """Create StatusAny stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return StatusAnyAdapter.validate_python(cls.create_json())
