# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
from typing import Union, Literal, List, Dict

from waylay.services.registry.models.stream_closing import StreamClosing


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from pydantic import Field
from waylay.services.registry.models.event_close import EventClose


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class StreamClosingStub:
    """StreamClosing unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> StreamClosing:
        """Create StreamClosing stub instance.
            include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return StreamClosing(
                event='close',
                data=''
            )
        else:
            return StreamClosing(
                event='close',
                data=''
            )
