# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.tag_or_tag_reference import TagOrTagReference

    TagOrTagReferenceAdapter = TypeAdapter(TagOrTagReference)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

tag_or_tag_reference_model_schema = json.loads(
    r"""{
  "title" : "TagOrTagReference",
  "description" : "A reference to a tag, or tag object.",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/TagReference"
  }, {
    "$ref" : "#/components/schemas/Tag"
  } ]
}
""",
    object_hook=with_example_provider,
)
tag_or_tag_reference_model_schema.update({"definitions": MODEL_DEFINITIONS})

tag_or_tag_reference_faker = JSF(
    tag_or_tag_reference_model_schema, allow_none_optionals=1
)


class TagOrTagReferenceStub:
    """TagOrTagReference unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return tag_or_tag_reference_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "TagOrTagReference":
        """Create TagOrTagReference stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                TagOrTagReferenceAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return TagOrTagReferenceAdapter.validate_python(
            json, context={"skip_validation": True}
        )
