# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.undeploy_job_status import UndeployJobStatus

    UndeployJobStatusAdapter = TypeAdapter(UndeployJobStatus)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

undeploy_job_status_model_schema = json.loads(
    r"""{
  "required" : [ "createdAt", "createdBy", "job", "operation", "request", "state", "type" ],
  "type" : "object",
  "properties" : {
    "operation" : {
      "type" : "string",
      "description" : "The type of operation that was executed."
    },
    "createdBy" : {
      "type" : "string",
      "description" : "The user identity that was used to execute the job."
    },
    "createdAt" : {
      "type" : "string",
      "description" : "The timestamp of when the job was created.",
      "format" : "date-time"
    },
    "processedAt" : {
      "type" : "string",
      "description" : "The timestamp of when the job has begun processing.",
      "format" : "date-time"
    },
    "finishedAt" : {
      "description" : "The timestamp of when the job has finished processing."
    },
    "attemptsMade" : {
      "type" : "number",
      "description" : "The number of retries that were attempted."
    },
    "type" : {
      "$ref" : "#/components/schemas/Undeploy_type"
    },
    "state" : {
      "$ref" : "#/components/schemas/JobStateResult"
    },
    "request" : {
      "$ref" : "#/components/schemas/UndeployArgs"
    },
    "result" : {
      "$ref" : "#/components/schemas/UndeployResult"
    },
    "function" : {
      "$ref" : "#/components/schemas/FunctionRef"
    },
    "job" : {
      "$ref" : "#/components/schemas/JobStatus"
    }
  }
}
""",
    object_hook=with_example_provider,
)
undeploy_job_status_model_schema.update({"definitions": MODEL_DEFINITIONS})

undeploy_job_status_faker = JSF(
    undeploy_job_status_model_schema, allow_none_optionals=1
)


class UndeployJobStatusStub:
    """UndeployJobStatus unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return undeploy_job_status_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "UndeployJobStatus":
        """Create UndeployJobStatus stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                UndeployJobStatusAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return UndeployJobStatusAdapter.validate_python(
            json, context={"skip_validation": True}
        )
