# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from waylay.services.registry.models.unhealthy_invokable_webscript_error import (
    UnhealthyInvokableWebscriptError,
)
from .invokable_webscript_response_entity_stub import (
    InvokableWebscriptResponseEntityStub,
)

from .invoke_internal_hal_link_stub import InvokeInternalHALLinkStub


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


class UnhealthyInvokableWebscriptErrorStub:
    """UnhealthyInvokableWebscriptError unit test stubs."""

    @staticmethod
    def create_instance(
        include_optional: bool = False,
    ) -> UnhealthyInvokableWebscriptError:
        """Create UnhealthyInvokableWebscriptError stub instance.
        include_optional -- if `True`, optional properties are included.
        """

        if include_optional:
            return UnhealthyInvokableWebscriptError(
                entity=InvokableWebscriptResponseEntityStub.create_instance(),
                links=InvokeInternalHALLinkStub.create_instance(),
                error="",
                code="",
            )
        else:
            return UnhealthyInvokableWebscriptError(
                entity=InvokableWebscriptResponseEntityStub.create_instance(),
                links=InvokeInternalHALLinkStub.create_instance(),
                error="",
                code="",
            )
