# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.registry.models.verify_query_v1 import VerifyQueryV1

    VerifyQueryV1Adapter = TypeAdapter(VerifyQueryV1)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

verify_query_v1_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "scaleToZero" : {
      "type" : "boolean",
      "description" : "Indicates whether the function needs to be scaled down after successful verification. If not set, the function is scaled to zero only if it was not active before this command."
    }
  },
  "additionalProperties" : false
}
""",
    object_hook=with_example_provider,
)
verify_query_v1_model_schema.update({"definitions": MODEL_DEFINITIONS})

verify_query_v1_faker = JSF(verify_query_v1_model_schema, allow_none_optionals=1)


class VerifyQueryV1Stub:
    """VerifyQueryV1 unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return verify_query_v1_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "VerifyQueryV1":
        """Create VerifyQueryV1 stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                VerifyQueryV1Adapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return VerifyQueryV1Adapter.validate_python(
            json, context={"skip_validation": True}
        )
