# coding: utf-8
"""Waylay Function Registry model tests.

This code was generated from the OpenAPI documentation of 'Waylay Function Registry'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import warnings

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS

try:
    from waylay.services.registry.models.verify_model_sync_response_v2 import (
        VerifyModelSyncResponseV2,
    )

    VerifyModelSyncResponseV2Adapter = TypeAdapter(VerifyModelSyncResponseV2)
    MODELS_AVAILABLE = True
except ImportError as exc:
    warnings.warn(f"Type adapter for VerifyModelSyncResponseV2 not available: {exc}")
    MODELS_AVAILABLE = False

verify_model_sync_response_v2_model_schema = json.loads(r"""{
  "required" : [ "entity", "message", "result" ],
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string"
    },
    "entity" : {
      "$ref" : "#/components/schemas/KfservingResponseV2"
    },
    "result" : {
      "$ref" : "#/components/schemas/VerifyResult"
    }
  },
  "description" : "Model Health Verified"
}
""")
verify_model_sync_response_v2_model_schema.update({"definitions": MODEL_DEFINITIONS})

verify_model_sync_response_v2_faker = JSF(
    verify_model_sync_response_v2_model_schema, allow_none_optionals=1
)


class VerifyModelSyncResponseV2Stub:
    """VerifyModelSyncResponseV2 unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return verify_model_sync_response_v2_faker.generate()

    @classmethod
    def create_instance(cls) -> "VerifyModelSyncResponseV2":
        """Create VerifyModelSyncResponseV2 stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return VerifyModelSyncResponseV2Adapter.validate_python(cls.create_json())
